
import { Poppins } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'


const poppins = Poppins({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <section className="bg-gradient-to-r from-slate-900 via-[#1e1b4b] to-slate-900 bg-no-repeat bg-cover  ">
          <main className="bg-[url('/grid.svg')]">
            <Navbar />
            <div className="">{children}</div>
            <Footer />
          </main>
        </section>
      </body>
    </html>
  )
}
